### ISSUE TITLE
As a user who has just finished signing up, I can read helpful hints and tips about what to do next

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#10]
**General Copy needed**
- [ ] Thank you for signing up
- [ ] What happens next (we save user's info so next time they don't need to go through webviews)
- [ ] Optional "we sent your message along" if user didn't skip submitting message
- [ ] Include tips for the next time user sends a message
- [ ] Reiterate who user's reps are, along with myreps email address
- [ ] Include links to FAQ and district permalink

![Page 3](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/signup__success.png)

**Comment by nickom** [comment]
**Thank you for signing up**
Thanks for signing up!

**What happens next (we save user's info so next time they don't need to go through webviews)**
You can now easily email all of the legislators who represent you in Congress without filling out the form again.

**Optional "we sent your message along" if user didn't skip submitting message**
We've sent your message to [Rep.Name @ opencongress.org][Sen.Name1 @ opencongress.org][Sen.Name2 @ opencongress.org].

**Include tips for the next time user sends a message**
Here are some tips for emailing Congress:
- **Keep it short** - Many congressional websites have a character or word limit and you can share more once a staffer responds to you.
- **You can only email your representatives** - Due to the way congressional websites are designed, we can only connect you to the members representing the address you provided us. Feel free to ask the members who represents you to forward your message to other members you’d like to contact. You can also mail a letter or call a member’s office by looking up that information here: [OpenCongress lookup tool]
- **Stick to one issue** - Keep your communication to a single topic and explain how the issue would affects you. This will help the office connect you with the relevant person.
- **Include a bill name/number if possible** - Look up bills on OpenCongress here [link]
- **Be respectful and don’t threaten anyone** - This is also true in other human communications.
- **We’re not Congress** - OpenCongress is operated by the Sunlight Foundation, a nonpartisan nonprofit dedicated to government transparency and accountability.

**Reiterate who user's reps are, along with myreps email address**
Based on the information you provided us, your representatives in Congress are:
[members listed]
Email all of them at once using MyReps @ opencongress.org

**Include links to FAQ and district permalink**
[don't think we need any copy for this]
