### ISSUE TITLE
As a user who wants or needs to update their info, I can read why I should do so

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#11]
**General Copy needed**
- [ ] Display user's email address their information is associated with
- [ ] Email-initiated version: Explain why information needs to be updated
- [ ] User-initiated version: Ask if their info changed, then same as above
- [ ] Errors: should be the same as those in the sign-up form

![](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/change-of-address__user-Initiated.png)
![](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/change-of-address__email-Initiated.png)

**Comment by nickom** [comment]
**Display user's email address their information is associated with**
Welcome back, user @ email.com! It’s been a while since you updated your information.

**Email-initiated version: Explain why information needs to be updated**
Please update your information to help us ensure we're delivering your messages to the correct representatives.

**User-initiated version: Ask if their info changed, then same as above** [I think this can be the same as above]
Please update your information to help us ensure we're delivering your messages to the correct representatives.

**Errors: should be the same as those in the sign-up form**
[Error message for when any field is missing]
Congressional offices require this field to accept a message.

[Error message for when zip-4 is missing (link to zip-4 lookup)]
Congressional offices require a ZIP-4 Code. Use this tool to find it.

[Error for when inputted address is determined invalid (no congressional district could be associated)]
Sorry! There does not appear to be a congressional district associated with this address. Double check your information or try using the congressional websites directly. [LINK]
