### ISSUE TITLE
As a user, I can read through an FAQ that answers common questions I may have about this service

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#13]
**Sections of Q+A needed**
- [ ] General questions about this service
- [ ] General section addressing common errors
- [ ] Questions about supporting our work

_Note: Leaving the contents of this page mostly up to @nickom. Have at it._

![FAQ Wireframe](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/faq.png)

**Comment by nickom** [comment]
### General questions

**What is this?**
Members of Congress don’t have official emails. This service makes navigating their required webforms as easy as emailing them and allows you to contact them via email after filling out your information once.

**Is there another way to contact Congress?**
Yes! You can call, fax or mail a message and show up to their offices in person to discuss issues that are important to you. Look up their contact information here. [http://www.usa.gov/Contact/US-Congress.shtml#Contact_Your_Representative_in_the_U.S._Congress]

**What are some tips on communicating with Congress?**
Keep it short - Many congressional websites have a character or word limit and you can share more once a staffer responds to you.

You can only email your representatives - Due to the way congressional websites are designed, we can only connect you to the members representing the address you provided us. Feel free to ask the members who represents you to forward your message to other members you’d like to contact. You can also mail a letter or call a member’s office by looking up that information here: [OpenCongress lookup tool]

Stick to one issue - Keep your communication to a single topic and explain how the issue would affects you. This will help the office connect you with the relevant person.

Include a bill name/number if possible - Look up bills on OpenCongress here [link]

Be respectful and don’t threaten anyone - This is also true in other human communications.

We’re not Congress - This service is operated by the Sunlight Foundation, a nonpartisan nonprofit dedicated to government transparency and accountability.

### Common errors

**Why isn't my message being sent?**
Message failures can occur for many reasons, some outside of your or our control.

Messages can fail when there are issues on the congressional webforms we're passing your message through or our system may need to be updated to reflect changes.

Sometimes errors in the information from the message can cause issues, such as a lengthy message that exceeds the limit on webforms, which is set individually be each congressional office. 

If the address you entered does not fall in the congressional district you're trying to send your message to or is not recognized by the congressional web form it can result in an unsent message.

### Supporting this work

**Who made this?**
The Sunlight Foundation [http://sunlightfoundation.com/], a nonpartisan nonprofit dedicated to government transparency and accountability, built this project to help connect citizens to their representatives in Congress. We're not affiliated with government and the open source code for this project is available on GitHub [https://github.com/sunlightlabs/the-phantom-mask].

**How can I get more involved?**
Please join our email list [http://sunlightfoundation.com/join/] to keep up with our latest work and donate here [https://sunlightfoundation.com/engage/donate/].

**Comment by nickom** [comment]
Some copy updates. Under "General questions" I would add this section:

**Why can I only select the three titles: Mr., Mrs. and Ms.?**
Many congressional webforms require a title, but there is no standard list across offices. Some include honorifics from medical, military and other professional fields, but the three options we provide are the minimum selection that spans all webforms.

How does that look @crdunwel ?

**Comment by crdunwel** [comment]
:+1:
