### ISSUE TITLE
Looks like emails are getting sent from "Open" instead of "OpenCongress"

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#45]
![screen shot 2015-07-09 at 3 30 27 pm](https://cloud.githubusercontent.com/assets/1198350/8666354/28c5848c-29be-11e5-971c-4ebcf2d330d6.png)

**Comment by crdunwel** [comment]
@heyitsolivia  See image below. I can change the name here, but the change may affect the current live service in unexpected ways (the sender name may be used in a boolean check, for instance). It's not really likely but since it's so easy to change then I'll leave it as is for now until we're ready to launch.

![screen shot 2015-07-20 at 4 54 33 pm](https://cloud.githubusercontent.com/assets/942819/8787099/123b068c-2f00-11e5-96eb-1bbf76367343.png)

**Comment by crdunwel** [comment]
I changed this @heyitsolivia . Closing.
