### ISSUE TITLE
As a user who is signing up for the service, I can read helpful hints that make the process easier

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#8]
**General Copy needed**
- [ ] Intro text that explains what the service does
- [ ] Tooltip that explains why the address field is required, including zip
- [ ] Hint to explain autofilled city and state
- [ ] Tooltip that explains why the phone number field field is required
- [ ] Terms of service agreement (external link)
- [ ] Reiterating the fact that the service is not affiliated with Congress
- [ ] Note for alternate method of contacting Congress should the user choose not to use our service

**Error Copy needed**
- [ ] Error message for when any field is missing
- [ ] Error message for when zip-4 is missing (link to zip-4 lookup)
- [ ] Error for when inputted address is determined invalid (no congressional district could be associated)

**Wireframes for Reference**
![Page 1](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/signup-p1.png)

![Page 1: autofill](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/signup-p1__autofill.png)

![Page 1: errors](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/signup-p1__zip4-error.png)

**Comment by nickom** [comment]
Let me know any edits or suggestions.

**Copy under box top left**:
Filling out a form every time you want to communicate with your members of Congress is tedious! 

**Copy under box top middle**:
We’re trying to make it a little easier by filling out the form once. Contacting Congress should be as easy as email.

**Copy under box top right**:
We'll securely save your information for one year and enable you to send messages to Congress via email.

**Tooltip that explains why the address field is required, including zip**:
We ask for your address and ZIP Code because congressional offices require them to send a message.

**Hint to explain autofilled city and state**
The City and State fields are based on your ZIP Code. Editing these may result in an unsuccessful message transmission.

**Tooltip that explains why the phone number field field is required**
We ask for your Phone Number because congressional offices require them to send a message.

**Terms of service agreement (external link)** [and maybe our privacy policy?]
I agree to the [terms of service](https://www.opencongress.org/terms).

**Reiterating the fact that the service is not affiliated with Congress**
**Members of Congress don’t have official emails**. This service makes navigating their required web forms as easy as emailing them. If you’d prefer to fill the web form of each member of Congress each time or would like another method of communication, look up your member of Congress here: [link to member lookup on OpenCongress]

This service is offered by the Sunlight Foundation and is **not** affiliated with Congress.

**Note for alternate method of contacting Congress should the user choose not to use our service**
Click here if you don't want to use this service or would like an alternative method to communicate with Congress.

**Error message for when any field is missing**
Congressional offices require this field to accept a message.

**Error message for when zip-4 is missing (link to zip-4 lookup)**
Congressional offices require a ZIP-4 Code. Use **this tool** to find it.

**Error for when inputted address is determined invalid (no congressional district could be associated)**
Sorry! There does not appear to be a congressional district associated with this address. Double check your information or try using the congressional websites directly. [LINK]

**Comment by heyitsolivia** [comment]
@nickom :100:

Where does the "click here" for lead to for this line?

> Click here if you don't want to use this service or would like an alternative method to communicate with Congress.

**Comment by crdunwel** [comment]
Same question as @heyitsolivia but otherwise :+1:

**Comment by nickom** [comment]
This?
http://www.usa.gov/Contact/US-Congress.shtml#Contact_Your_Representative_in_the_U.S._Congress

**Comment by heyitsolivia** [comment]
@nickom On second glance, these two parts seem pretty similar in language and objectives, and will appear next to each other. Can we combine these and use a single link?

> If you’d prefer to fill the web form of each member of Congress each time or would like another method of communication, look up your member of Congress here: [link to member lookup on OpenCongress]

and 

> Click here if you don't want to use this service or would like an alternative method to communicate with Congress.

**Comment by nickom** [comment]
Yeah good call, let's just go with the second (shorter) version and link here: http://www.usa.gov/Contact/US-Congress.shtml#Contact_Your_Representative_in_the_U.S._Congress

**Comment by heyitsolivia** [comment]
:+1:
