### ISSUE TITLE
As a user who is reviewing their email message after signup, I can understand who I can (and can't) send messages to

### ISSUE THREAD

**Issue by heyitsolivia** [sunlightlabs/the-phantom-mask#9]
**General Copy needed**
- [ ] Congressional district listed
- [ ] User's representatives email and myreps email listed
- [ ] Secondary "Do Not Send Message" button (skips sending message, and continues to success page)

**Error Copy needed**
- [ ] Cannot contact congressperson who doesn't represent you
- [ ] Cannot recognize an invalid email address

![Page 2](https://raw.githubusercontent.com/sunlightlabs/the-phantom-mask/master/design/wireframes/views/signup-p2.png)

**Comment by nickom** [comment]
**Congressional district listed**
Based on the address you gave us, you're in congressional district [State]-[Number]. Here's who represents you in the U.S. Congress, select the members you would like to contact and finish sending your message below:

[members listed]

**Cannot contact congressperson who doesn't represent you**
Note: Due to restrictions imposed by Congress, you can only send a message through this system to the members representing the address you provided us. Feel free to ask the members who represent you to forward your message to other members you’d like to contact. You may contact any member if you mail a letter or call a member’s office. Look up their information on OpenCongress here. [link to OpenCongress lookup)

**Cannot recognize an invalid email address**
We did not recognize the email address you entered, please select which of your members you would like to contact and complete your message.

**Buttons at the bottom** I think these buttons should say:
Send this message now and complete sign up
Discard message and complete sign up
